evaluation_enzo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('exchange.urls')),  # Inclure les URLs de l'application exchange
    path('accounts/', include('django.contrib.auth.urls')),  # Inclure les URLs d'authentification par défaut
]

exchange/urls.py
from django.urls import path
from . import  views

urlpatterns = [
    path('', views.home, name='home'),# Lien vers la vue home    #
    path('dashboard/', views.dashboard, name='dashboard'),
    path('add-skill/', views.add_skill, name='add_skill'),
    path('add-availability/', views.add_availability, name='add_availability'),
    path('accounts_login/', views.login_view, name='login'),  # Changement ici vers login_view
    path('accounts/profile/', views.profile, name='profile'),
    path('accounts/password_change/', views.password_change, name='password_change'),
    path('accounts/logout/', views.logout_view, name='logout'),
    path('accounts/edit_profile/', views.edit_profile, name='edit_profile'),
    path('accounts/logout/', views.logout_view, name='logout'),
    path('accounts/add-activity/', views.add_activity, name='add_activity'),
    path('add-exchange/', views.add_exchange, name='add_exchange'),
    path('my-exchanges/', views.my_exchanges, name='my_exchanges'),  # Ajoutez ce chemin

]

exchange/models.py
from django.contrib.auth.models import User
from django.db import models

# Modèle pour l'activité
class Activity(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    date = models.DateTimeField(auto_now_add=True)
    location = models.CharField(max_length=255, default='Default Location')  # Valeur par défaut

    def __str__(self):
        return self.title


class Skill(models.Model):
    id = models.AutoField(primary_key=True)  # Ajoutez explicitement l'ID si nécessaire
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    level = models.IntegerField()
    def __str__(self):
        return self.name

# Modèle pour la disponibilité
class Availability(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)  # Utilisateur lié
    skill = models.ForeignKey(Skill, on_delete=models.CASCADE)  # Compétence liée
    day = models.DateField()  # Date de disponibilité
    time = models.TimeField()  # Exemple de champ time

    def __str__(self):
        return f"{self.user.username} - {self.skill.name} on {self.date}"

# Modèle pour l'échange de compétences
class Exchange(models.Model):
    requester = models.ForeignKey(User, on_delete=models.CASCADE, related_name="requested_exchanges")  # Demandeur
    provider = models.ForeignKey(User, on_delete=models.CASCADE, related_name="provided_exchanges")  # Fournisseur de la compétence
    skill = models.ForeignKey(Skill, on_delete=models.CASCADE)  # Compétence concernée
    level = models.IntegerField()

    date = models.DateField()  # Date de l'échange

    def __str__(self):
        return f"{self.requester.username} booked with {self.provider.username} for {self.skill.name} on {self.date}"

exchange/forms.py
from django import forms
from django.contrib.auth.models import User  # Importer le modèle User de Django
from .models import Skill, Availability, Activity, Exchange

class ActivityForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = ['title', 'description', 'location']  # Inclure 'location' dans le formulaire

    # Vous pouvez ajouter des validations supplémentaires si nécessaire
    def clean_title(self):
        title = self.cleaned_data.get('title')
        if not title:
            raise forms.ValidationError("Ce champ est obligatoire.")
        return title

    def clean_description(self):
        description = self.cleaned_data.get('description')
        if not description:
            raise forms.ValidationError("Ce champ est obligatoire.")
        return description

class SkillForm(forms.ModelForm):
    class Meta:
        model = Skill
        fields = ['name', 'level']  # Exemple de champs, à adapter selon votre modèle

class AvailabilityForm(forms.ModelForm):
    class Meta:
        model = Availability
        fields = ['day', 'time']  # Exemple de champs, à adapter selon votre modèle


class ProfileUpdateForm(forms.ModelForm):
    first_name = forms.CharField(label='Prénom', required=False, max_length=30)
    last_name = forms.CharField(label='Nom', required=False, max_length=30)
    email = forms.EmailField(label='Adresse email', required=False)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

class ExchangeForm(forms.ModelForm):
    class Meta:
        model = Exchange
        fields = ['provider', 'skill', 'date']  # Champs disponibles dans le formulaire
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
        }

exchange/views.py
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.shortcuts import render, redirect

from .forms import SkillForm, AvailabilityForm, \
    ActivityForm, ExchangeForm, ProfileUpdateForm  # Assurez-vous d'avoir défini ces formulaires dans forms.py
from .models import Skill, Activity, Exchange


# Vue pour la page d'accueil
def home(request):
    skills = Skill.objects.all()
    skills_list = [skills[i:i + 3] for i in range(0, len(skills), 3)]  # Diviser les compétences en trois colonnes
    return render(request, 'exchange/home.html', {'skills_list': skills_list})


# Vue pour le tableau de bord
@login_required
def dashboard(request):
    activities = Activity.objects.all()
    return render(request, 'exchange/dashboard.html', {'activities': activities})


# Vue pour ajouter une compétence
@login_required
def add_skill(request):
    if request.method == 'POST':
        form = SkillForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('dashboard')
    else:
        form = SkillForm()
    return render(request, 'exchange/add_exchange.html', {'form': form})


# Vue pour ajouter la disponibilité
@login_required
def add_availability(request):
    if request.method == 'POST':
        form = AvailabilityForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('dashboard')
    else:
        form = AvailabilityForm()
    return render(request, 'exchange/add_availability.html', {'form': form})


# Vue pour la connexion
def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('dashboard')
    else:
        form = AuthenticationForm()
    return render(request, 'exchange/accounts/login.html', {'form': form})


# Vue pour afficher et modifier le profil
@login_required
def profile(request):
    return render(request, 'exchange/accounts/profile/profile.html')


# Vue pour changer le mot de passe
@login_required
def password_change(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('profile')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'exchange/accounts/password_change.html', {'form': form})


# Vue pour déconnecter l'utilisateur
def logout_view(request):
    auth_logout(request)
    return redirect('home')


# Vue pour éditer le profil de l'utilisateur
@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = ProfileUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('profile')  # Redirige vers la page de profil après mise à jour
    else:
        form = ProfileUpdateForm(instance=request.user)

    return render(request, 'exchange/accounts/edit_profile.html', {'form': form})

# Vue pour ajouter une activité
@login_required
def add_activity(request):
    if request.method == 'POST':
        form = ActivityForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('dashboard')
    else:
        form = ActivityForm()
    return render(request, 'exchange/accounts/add_activity.html', {'form': form})

@login_required
def add_exchange(request):
    if request.method == 'POST':
        form = ExchangeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('dashboard')  # Redirige vers le tableau de bord après déclaration
    else:
        form = ExchangeForm()

    return render(request, 'exchange/add_exchange.html', {'form': form})

def my_exchanges(request):
    exchanges = Exchange.objects.filter(requester=request.user)
    return render(request, 'exchange/my_exchanges.html', {'exchanges': exchanges})

exchange/templates/exchange/accounts/add_activity.html
<h1>Ajouter une Activité</h1>

<!-- Vérifier si des messages d'erreur existent -->
{% if form.errors %}
  <div class="alert alert-danger">
    <p>Veuillez corriger les erreurs suivantes :</p>
    <ul>
      {% for field in form %}
        {% for error in field.errors %}
          <li>{{ error }}</li>
        {% endfor %}
      {% endfor %}
    </ul>
  </div>
{% endif %}

<!-- Affichage du formulaire -->
<form method="post" class="form">
  {% csrf_token %}

  <div class="form-group">
    <label for="id_title">Titre de l'activité</label>
    {{ form.title }}  <!-- Affiche le champ title -->
  </div>

  <div class="form-group">
    <label for="id_description">Description</label>
    {{ form.description }}  <!-- Affiche le champ description -->
  </div>

  <div class="form-group">
    <label for="id_date">Date</label>
    {{ form.date }}
  </div>

  <div class="form-group">
    <label for="id_location">Emplacement</label>
    {{ form.location }}
  </div>

  <button type="submit" class="btn btn-primary">Ajouter l'activité</button>
</form>

<hr>
<a href="{% url 'dashboard' %}" class="btn btn-secondary">Retour au tableau de bord</a>

exchange/templates/exchange/accounts/edit_profile.html
{% block content %}
<h2>Modifier le profil</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Mettre à jour</button>
</form>
{% endblock %}

exchange/templates/exchange/accounts/password_change.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Accueil - Échange de Compétences</title>
    <style>
        *{
        margin: 0;
        padding:0;
        }
        header{
        background-color: grey;
        color: red;
        }header h1,p{
        text-align: center;
        }
        nav{
                background-color: blue;

        }
        .skills-container {
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;
}

.skills-row {
    display: flex;
    flex-direction: row;
    justify-content: space-between;
    width: 100%;
}

.skill-card {
    width: 30%; /* Chaque carte occupe 30% de la largeur de l'écran */
    margin: 10px 0;
    padding: 15px;
    border: 1px solid #ddd;
    border-radius: 5px;
    box-shadow: 0 0 5px rgba(0, 0, 0, 0.1);
    background-color: #f9f9f9;
}

.skill-card h3 {
    margin: 0;
    font-size: 1.2em;
}

.skill-card p {
    font-size: 1em;
    color: #333;
}
        .column{
        background-color: red;
        }
        .exchanges{
        background-color: red;
        }
        form{
        text-align:center;
        }
    </style>
</head>
<body>
    <header>
        <h1>Changement de mot passe</h1>
    </header>
    <nav>

{% block content %}
<h2>Change Password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Change Password</button>
</form>
{% endblock %}


</body>
</html>